quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import dashboard

from perguntas.api.viewsets import PerguntaAllViewSet, PerguntaInformaticaViewSet, PerguntaLogicaViewSet, PerguntaDireitoViewSet

from rest_framework import routers


router = routers.DefaultRouter()
router.register('question-all', PerguntaAllViewSet, basename='Pergunta'),
router.register('question-computing', PerguntaInformaticaViewSet, basename='Pergunta-Informatica'),
router.register('question-logica', PerguntaLogicaViewSet, basename='Pergunta-logica'),
router.register('question-direito', PerguntaDireitoViewSet, basename='Pergunta-direito'),

urlpatterns = [
    path('api/v1/', include(router.urls)),

    path('', dashboard),
    path('accounts/', include('accounts.url')),
    path('questoes/', include('perguntas.url')),
    path('resposta/', include('respostas.url', namespace='respostas')),
    path('summernote/', include('django_summernote.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "handlers.views.page_not_404"

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
import os

def user_directory_path(instance, filename):
    """
    Define o caminho onde os arquivos serão salvos no S3, organizados por usuário.
    Exemplo: 'users/user-email-com/meuarquivo.pdf'
    """
    email_slug = instance.email.replace("@", "-at-").replace(".", "-")  # Garante unicidade
    ext = filename.split('.')[-1]  # Pega a extensão do arquivo
    new_filename = f"{uuid.uuid4()}.{ext}"  # Nome único para evitar sobrescrições
    return os.path.join("users", email_slug, new_filename)


class CostumerUser(AbstractUser):
    sexo = models.CharField(max_length=15, blank=True, null=True, default=None)
    biografia = models.TextField(blank=True)
    imagem = models.ImageField(blank=True, null=True, upload_to=user_directory_path)

    def get_file_url(self):
        """Retorna a URL da imagem ou um placeholder caso esteja vazia."""
        if self.imagem:  # Evita erro caso a imagem esteja vazia
            return self.imagem.url

templates/accounts_templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dashboard</title>
    <link rel="icon" href="{% static 'img/universidade.png' %}">
    <link rel="stylesheet" href="{% static 'css_accounts/dashboard.css' %}" />
    <link rel="stylesheet" href="{% static 'css_accounts/animations.css' %}" />
    </head>
  <body>
    <header>
      <div class="container-header">
        <h1>Dashboard</h1>
        <img src="{% static 'img/logo.png' %}" alt="logo" />
        <img
          src="{% static 'img/botao-de-menu.png' %}"
          id="menu-hamburgue"
          alt="menu"
          onclick="openNav()"
        />
      </div>
    </header>
    <nav id="mySidepanel" class="sidepanel">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
      <div class="box-container" id="box-container">
        <h1>Máterias</h1>
        <hr />
        <input
          type="text"
          placeholder="Pesquisar matéria..."
          id="myInput"
          onkeyup="filterFunction()"
        />
        <a href="{% url 'perguntas:categoria_materia' 'Português' %}"
          >Português<img
            src="{% static 'img/livros-educativos.png' %}"
            alt="português"
        /></a>
        <a href="{% url 'perguntas:categoria_materia' 'Informática' %}"
          >Informática<img
            src="{% static 'img/informatica.png' %}"
            alt="informatica"
        /></a>
        <a href="{% url 'perguntas:categoria_materia' 'Lógica' %}"
          >Mais uma vez e la vamos nos<img
            src="{% static 'img/pensamento-logico.png' %}"
            alt="logica"
        /></a>
        <a href="{% url 'perguntas:categoria_materia' 'Estatística' %}"
          >Samio Pereira dos Santos<img
            src="{% static 'img/estatisticas.png' %}"
            alt="estatisca"
        /></a>
        <a href="{% url 'perguntas:categoria_materia' 'Direito' %}"
          >Direito<img
            src="{% static 'img/balanca-de-peso.png' %}"
            alt="direito"
        /></a>
        <a href="{% url 'perguntas:categoria_materia' 'Contabilidade' %}"
          >Mais uma tentativa<img
            src="{% static 'img/contabilidade.png' %}"
            alt="contabilidade"
        /></a>
        <a href="{% url 'perguntas:categoria_materia' 'Criminologia' %}"
          >Criminologia<img
            src="{% static 'img/criminologia.png' %}"
            alt="contabilidade"
        /></a>
      </div>

      <div class="logout">
        <a href="{% url 'logout' %}"
          >Sair<img src="{% static 'img/logout.png' %}" alt="logout"
        /></a>
      </div>
    </nav>

    <main id="content">
      <div class="spinner">
        <div class="rect1"></div>
        <div class="rect2"></div>
        <div class="rect3"></div>
        <div class="rect4"></div>
        <div class="rect5"></div>
      </div>
      <section class="secao" style="display: none">
        {% if messages %}
          {% for message in messages %}
            <div class="notification">
              {{ message }}
              <span class="notification-progress"></span>
            </div>
          {% endfor %}
        {% endif %}
        
          <div class="container-user">
          <div class="perfil">
            {% if user.imagem %}
              <img src="{{user.imagem.url}}" alt="foto-perfil" />
            {% else %}
              {% if user.sexo == "Masculino" %}
                <img src="{% static 'img/avatar_masculino.jpg' %}" alt="foto-perfil" />
              
              {% elif user.sexo == "Feminino" %}
                <img src="{% static 'img/avatar_feminino.jpg' %}" alt="foto-perfil" />

              {% elif user.sexo == None %}
                <img src="{% static 'img/user2.png' %}" alt="foto-perfil" />
              {% endif %}
            {% endif %}
            <a href="{% url 'perfil_user' user.id %}"><span>Editar Perfil</span></a>
            <p>{{user.first_name}} {{user.last_name}}</p>
          </div>
        </div>
        <div class="container-result">
          <div class="questions">
            <img
              src="{% static 'img/verificacao-preto.png' %}"
              alt="circulo-preto"
            /><br /><br />
            <span>{{total_respostas}}</span>
            <p>Questões Resolvidas</p>
          </div>
        </div>
        <div class="container-result">
          <div class="questions">
            <img
              src="{% static 'img/verificacao-verde.png' %}"
              alt="circulo-preto"
            /><br /><br />
            <span style="color: green">{{respostas_certas}}</span>
            <p style="color: green">Respostas Corretas</p>
          </div>
        </div>

        <div class="container-result">
          <div class="questions">
            <img
              src="{% static 'img/verificacao-vermelho.png' %}"
              alt="circulo-preto"
            /><br /><br />
            <span style="color: red">{{respostas_erradas}}</span>
            <p style="color: red">Respostas Erradas</p>
          </div>
        </div>

        <div class="container-delete">
          <div class="box-delete">
            <button
              class="button1"
              onclick="document.getElementById('id01').style.display='block'"
            >
              Zerar samio santos
            </button>
          </div>
        </div>

        <div class="container-pdf">   
          <div class="box-pdf">
            <a class="button1" href="{% url 'my-pdf' %}" target="blank">Gerar relatorio samy santos</a>
          </div>       
        </div>
      </section>
      <aside class="aside" style="display: none">
        <div class="graphic">
          <input
            type="hidden"
            id="respostas_certas"
            value="{{respostas_certas}}"
          />
          <input
            type="hidden"
            id="respostas_erradas"
            value="{{respostas_erradas}}"
          />
          <canvas id="myChart"></canvas>
        </div>
        <div class="graphic1">
          {% if total_respostas != 0 %}
            <input type="hidden" id="portugues_certas" value="{{portugues_certas}}"/>
            <input type="hidden" id="portugues_erradas" value="{{portugues_erradas}}"/>
            <input type="hidden" id="informatica_certas" value="{{informatica_certas}}"/>
            <input type="hidden" id="informatica_erradas" value="{{informatica_erradas}}"/>
            <input type="hidden" id="logica_certas" value="{{logica_certas}}"/>
            <input type="hidden" id="logica_erradas" value="{{logica_erradas}}"/>
            <input type="hidden" id="estatistica_certas" value="{{estatistica_certas}}"/>
            <input type="hidden" id="estatistica_erradas" value="{{estatistica_erradas}}"/>
            <input type="hidden" id="direito_certas" value="{{direito_certas}}"/>
            <input type="hidden" id="direito_erradas" value="{{direito_erradas}}"/>
            <input type="hidden" id="contabilidade_certas" value="{{contabilidade_certas}}"/>
            <input type="hidden" id="contabilidade_erradas" value="{{contabilidade_erradas}}"/>
            <input type="hidden" id="criminologia_certas" value="{{criminologia_certas}}"/>
            <input type="hidden" id="criminologia_erradas" value="{{criminologia_erradas}}"/>

            <canvas id="myChartBar" width="400" height="200"></canvas>
          {% endif %}
          <button
            class="button2"
            onclick="document.getElementById('id01').style.display='block'"
          >
            Zerar questões
          </button>
          
          <a class="button2" href="{% url 'my-pdf' %}" target="blank">Gerar relatorio em PDF</a>

        </div>

        <div id="id01" class="modal">
          <span
            class="close"
            title="Fechar"
            onclick="document.getElementById('id01').style.display='none'"
            >×</span
          >
          <form
            class="modal-content"
            method="POST"
            action="{% url 'perguntas:deletar_questoes_resolvidas' %}"
          >
            {% csrf_token %}

            <div class="container">
              <h1>
                Todas as estatísticas e histórico de questões respondidas serão
                apagados.
              </h1>
              <p>
                Essa ação não poderá ser revertida! Para prosseguir com essa
                ação, digite a seguinte frase para confirmar:
              </p>
              <p class="frase">Desejo zerar minhas estatísticas</p>
              <input type="text" id="frase" placeholder="Digite a frase aqui" />

              <div class="clearfix">
                <button
                  type="submit"
                  class="deletebtn"
                  name="delete"
                  value="Deletar"
                  disabled
                  onclick="document.getElementById('id01').style.display='none'"
                >
                  Delete
                </button>
              </div>
            </div>
          </form>
        </div>
      </aside>
    </main>

    <footer class="footer" style="display: none">
      <p>&copy; | Desenvolvido por Samio Santos</p>
    </footer>
    
    <script src="{% static 'scripts/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'scripts/graphic.js' %}"></script>
  </body>
</html>

templates/accounts_templates/email_template.html
Você está recebendo este email, porque solicitou a redefinição da senha da sua conta em {{site_name}}.

Por favor, acesse a seguinte página e escolha uma nova senha:

{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Se você não deseja redefinir suas credenciais, apenas ignore esta mensagem e nada será alterado.

Obrigado por usar nosso site!

Obs: Não responda este e-mail.

templates/accounts_templates/locked.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Locked</title>
    <link rel="icon" href="{% static 'img/universidade.png' %}">
    <link rel="stylesheet" href="{% static 'css_accounts/menu.css' %}" />
    <link rel="stylesheet" href="{% static 'css_accounts/locked.css' %}" />
</head>
<body>
    <main>
        <div class="box">
            <div class="container">
                <h2>Usuário Bloqueado!</h2>
                <ul>
                    <li>Você excendeu o limite de {{ failure_limit }} tentativas de login!</li>
                    <li>Seu usuário está bloqueado por {{ cooloff_timedelta }} minutos!</li>
                    <li>Tente novamente mais tarde!</li>
                    <li>Obrigado!</li>
                </ul>
                <a href="{% url 'login' %}">Voltar para tela de login</a>
            </div>
        </div>
    </main>
</body>
</html>

templates/accounts_templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"
    />
    <title>Login</title>
    <link rel="icon" href="{% static 'img/universidade.png' %}" />
    <link rel="stylesheet" href="{% static 'css_accounts/menu.css' %}" />
    <link rel="stylesheet" href="{% static 'css_accounts/login.css' %}" />

    <link
      href="{% static 'fontawesome-free-5.13.0-web/css/fontawesome.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'fontawesome-free-5.13.0-web/css/brands.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'fontawesome-free-5.13.0-web/css/solid.css' %}"
      rel="stylesheet"
    />
  </head>
  <body>
    <main>
      {% if not user.is_authenticated %}
      <form action="{% url 'login' %}" method="POST" name="form-login">
        {% csrf_token %}
        <fieldset class="container">
          {% if messages %}
            {% for message in messages %}
              {% if message.tags == "alert-success" %}
                <div class="notification">
                  {{ message }}
                  <span class="notification-progress"></span>
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}
          <div class="box">
            <img id="icon" src="{% static 'img/user.png' %}" alt="Login" />
            <h1>Log In</h1>
            
            {% if notUser %}
              {% if messages %}
                {% for message in messages %}
                  <div class="{{ message.tags }}" role="alert">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endif %}

            <div class="user">
              <i class="fas fa-user"></i>
              <input
                type="text"
                name="user"
                value="{{request.POST.user}}"
                id="username"
                placeholder="Email"
           
                required
              />
              {% if invalid %}
                {% if messages %}
                  {% for message in messages %}
                    <div class="{{ message.tags }}input" role="alert">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
              {% endif %}
            </div>
            

            <div class="user">
              <i class="fas fa-unlock-alt"></i>
              <input
                type="password"
                name="password"
                id="password"
                maxlength="45"
           
                placeholder="Password"
                required
              />

              <img
                id="hide"
                src="{% static 'img/escondido.png' %}"
                alt="MostraSenha"
                onclick="mostraSenha()"
              />
              {% if invalid %}
                {% if messages %}
                  {% for message in messages %}
                    <div class="{{ message.tags }}input" role="alert">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
              {% endif %}
            </div>

            <div class="reset-password">
              <a href="{% url 'register' %}">Cadastra-se</a>
            </div>

            <div class="reset-password">
              <a href="{% url 'reset_password' %}">Esqueceu a senha</a>
            </div>

            <div class="login-bnt">
              <button class="bnt" type="submit" name="enter">Entrar</button>
            </div>

            <h5>Conecte-se com:</h5>
            <div class="conect">
              <a href="{% url 'social:begin' 'github' %}">
                <img src="{% static 'img/github.png' %}" alt="login-github" />
              </a>

              <a href="{% url 'social:begin' 'google-oauth2' %}">
                <img src="{% static 'img/google.png' %}" alt="login-google" />
              </a>
            </div>
          </div>
        </fieldset>
      </form>
      {% else %}
      <div class="container-logado">
        <div>
          Você já está logado com usuário <span>{{ user }}</span>
          <a href="{% url 'logout' %}">clique aqui</a>
          para sair.<br />
          <button>
            <a href="{% url 'dashboard' %}"
              ><i class="fas fa-arrow-circle-left"></i> Voltar para o
              Dashboard</a
            >
          </button>
        </div>
      </div>
      {% endif %}
    </main>
    <script src="{% static 'scripts/script.js' %}"></script>
  </body>
</html>

templates/accounts_templates/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <title>Password reset</title>
    <link rel="icon" href="{% static 'img/universidade.png' %}">
    <link rel="stylesheet" href="{% static 'css_accounts/password.css' %}"/>
    <link rel="stylesheet" href="{% static 'css_accounts/menu.css' %}" />
  </head>
  <body>
    <header>
      <div class="container">
        <a href="{% url 'login' %}">
          <h1>Redefinição de senha</h1>
          <img
            id="icone-login"
            src="{% static 'img/rotation-lock.png' %}"
            alt="cadastro"
          />
        </a>
      </div>
    </header>

    <main>
      <section>
        <h3>Recuperar senha</h3>

        <p>
          Esqueceu sua senha? Insira seu endereço de e-mail abaixo e enviaremos
          instruções para configurar uma nova senha.
        </p>
        <form method="post">
          {% csrf_token %} 
          {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }} 
                {{ field }}
                <input id="button_reset" type="Submit" name="SendEmail" title="Enviar" value="Enviar"/>
            </div>
          {% endfor %}
        </form>
      </section>
    </main>

    <footer style="position: relative; bottom: -46px;">
      <p>&copy; | Desenvolvido por Samio Santos</p>
    </footer>
  </body>
</html>

templates/accounts_templates/password_reset_form.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <title>Password reset</title>
    <link rel="icon" href="{% static 'img/universidade.png' %}">
    <link rel="stylesheet"href="{% static 'css_accounts/password_form.css' %}"/>
    <link rel="stylesheet" href="{% static 'css_accounts/menu.css' %}" />
  </head>
  <body>
    <header>
      <div class="container">
        <h1>Redefinição de senha</h1>
        <img
          id="icone-login"
          src="{% static 'img/rotation-lock.png' %}"
          alt="cadastro"
        />
      </div>
    </header>

    <main>
      <aside>
        <h3> Digite a nova senha </h3>
        
        {% if validlink %}
          <p> Por favor, digite sua nova senha duas vezes para que possamos verificar se você a digitou corretamente.</p>
          
          <form method="POST">
            {% csrf_token %} 
            {{form}}
            
            <div id="Valid-password">
              <h3>A senha deve conter o seguinte:</h3>
              <p id="capital" class="invalid">Uma letra <b>maiúscula</b></p>
              <p id="letter" class="invalid">Uma letra <b>minúscula</b></p>
              <p id="number" class="invalid">Um<b> numero</b></p>
              <p id="length" class="invalid">Mínimo <b>8 caracteres</b></p>
              <p id="repeat-password" class="invalid">As<b> Senhas</b> são iguais</p>
            </div>
            <button type="submit" id="button_reset"name="Update_Password" title="Enviar">Enviar</button>
          </form>
        {% else %}
        <div class="container-info">
          <p style="color: red;">
            Link expirado! Faça o reenvio do link novamente.
          </p>

          <a href="{% url 'login' %}">
            Volta para tela de login
          </a>
        </div>
        {%endif %}
      </aside>
    </main>
  <script src="{% static 'scripts/script.js' %}"></script>
  </body>
</html>

templates/accounts_templates/perfil_user.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <title>Perfil</title>
    <link rel="icon" href="{% static 'img/universidade.png' %}">
    <link rel="stylesheet" href="{% static 'css_accounts/perfil_user.css' %}" />
    <link
      href="{% static 'fontawesome-free-5.13.0-web/css/fontawesome.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'fontawesome-free-5.13.0-web/css/brands.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'fontawesome-free-5.13.0-web/css/solid.css' %}"
      rel="stylesheet"
    />
  </head>
  <body>
    <header style="position: initial;">
      <div class="container">
        <a href="{% url 'dashboard' %}">
          <h1>Área - Perfil</h1>
        </a>
      </div>
    </header>

    <main>

      <button class="btn-back" onclick="history.back()">
        <i class="fas fa-arrow-left"></i>
      </button>

      <form
        action="{% url 'perfil_user' user.id %}"
        method="POST"
        enctype="multipart/form-data"
      >
        {% csrf_token %} 
        <div class="img-block">
          {% if user.imagem %}
            <img class="img-perfil" src="{{user.imagem.url}}" alt="foto-perfil" />
          {% else %}
            {% if user.sexo == "Masculino" %}
              <img class="img-perfil" src="{% static 'img/avatar_masculino.jpg' %}" alt="foto-perfil" />
            
            {% elif user.sexo == "Feminino" %}
              <img class="img-perfil" src="{% static 'img/avatar_feminino.jpg' %}" alt="foto-perfil" />
            {% endif %}
          {% endif %}

        </div>

        <div class="input-block-img">
          <div>
            <label for="file">
              <i class="fas fa-upload"></i>
              Foto Perfil
              <input type="file" name="imagem" accept="image/*" id="file">
            </label>
          </div>
        </div>
        
        <div class="input-block">
          <label for="id_first_name">Nome:</label>
          {{ form.first_name }}
        </div>

        <div class="input-block">
          <label for="id_last_name">Sobrenome:</label>
          {{ form.last_name }}
        </div>


        <div class="input-block">
          <label for="id_email">E-mail:</label>
          {{ form.email }}
        </div>

        <div class="input-block">
          <label for="sexo">Sexo:</label>
          <select id="sexo" name="sexo">
            <option value="{{user.sexo}}" selected disabled>{{user.sexo}}</option>
            <option value="Masculino">Masculino</option>
            <option value="Feminino">Feminino</option>
          </select>
        </div>

        <div class="input-block">
          <label for="id_biografia">Biografia:</label>
          {{ form.biografia }}
        </div>

        <button class="bnt-submit" type="submit">Salvar</button>
      </form>
    </main>
    
    <script src="{% static 'scripts/script.js' %}"></script>
  </body>
</html>

templates/accounts_templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <title>Cadastro</title>
    <link rel="icon" href="{% static 'img/universidade.png' %}">
    <link rel="stylesheet" href="{% static 'css_accounts/menu.css' %}" />
    <link rel="stylesheet" href="{% static 'css_accounts/register.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  </head>
  <body>
    <header>
      <div class="container">
        <a href="{% url 'login' %}">
          <h1>Cadastro</h1>
          <img id="icone-login" src="{% static 'img/cadastro.png' %}" alt="cadastro" />
        </a>
      </div>
    </header>
    <main>
      <form action="{% url 'register' %}" method="POST" name="form-login">
        {% csrf_token %}
        <fieldset>
          {% if messages %}
            {% for message in messages %}
              <div class="{{ message.tags }}" role="alert">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          <div class="input-block">
            <label for="nome">Nome: </label><br />
            <input type="text" name="nome" value="{{request.POST.nome}}" id="nome" />
          </div>

          <div class="input-block">
            <label for="Snome">Sobrenome:</label><br />
            <input type="text" name="Snome" value="{{request.POST.Snome}}" id="Snome" />
          </div>

          <div class="input-block">
            <label for="email">E-mail:</label><br />
            <input type="email" name="email" value="{{request.POST.email}}" id="email" />
          </div>

          <div class="input-block">
            <label for="sexo">Sexo:</label><br />
            <select id="sexo" name="sexo">
              <option value="None" selected disabled>selecione o sexo:</option>
              <option value="Masculino">Masculino</option>
              <option value="Feminino">Feminino</option>
            </select>
          </div>

          <div class="input-block">
            <label for="password">Senha:</label><br />
            <input type="password" name="password" id="id_new_password1" maxlength="48"/>
          </div>
          
          <div class="input-block">
            <label for="Rsenha">Repetir senha:</label><br />
            <input type="password" name="Rsenha" id="id_new_password2" maxlength="48"/>
          </div>
          
          <div id="Valid-password">
            <h3>A senha deve conter o seguinte:</h3>
            <p id="capital" class="invalid">Uma letra <b>maiúscula</b></p>
            <p id="letter" class="invalid">Uma letra <b>minúscula</b></p>
            <p id="number" class="invalid">Um<b> numero</b></p>
            <p id="length" class="invalid">Mínimo <b>8 caracteres</b></p>
            <p id="repeat-password" class="invalid">As<b> Senhas</b> são iguais</p>
          </div>

        </fieldset>

        <button type="submit" name="button" title="Cadastrar">Cadastrar</button>
      </form>
      
      <footer>
        <p>&copy; | Desenvolvido por Samio Santos</p>
      </footer>
    </main>
  <script src="{% static 'scripts/script.js' %}"></script>
  </body>
</html>

templates/accounts_templates/reset_password_sent.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <title>Password reset</title>
    <link rel="icon" href="{% static 'img/universidade.png' %}">
    <link rel="stylesheet" href="{% static 'css_accounts/password.css' %}"/>
    <link rel="stylesheet" href="{% static 'css_accounts/menu.css' %}" />
  </head>
  <body>
    <header>
      <div class="container">
        <a href="{% url 'login' %}">
          <h1>Redefinição de senha</h1>
          <img
            id="icone-login"
            src="{% static 'img/rotation-lock.png' %}"
            alt="cadastro"
          />
        </a>
      </div>
    </header>

    <main>
      <section>
        <h3>Redefinição de senha enviada</h3>
        <div class="container-text">
          <p>
            Nós te enviamos um email com instruções para configurar sua nova senha, se uma conta existe com o e-mail fornecido, você receberá uma mensagem em breve.
          </p>
          <br>
          <p>
            Se você não recebeu um email, por favor certifique-se que você forneceu um endereço de e-mail válido e verifique sua caixa de spam.
          </p>
        </div>
      </section>
    </main>

    <footer>
      <p>&copy; | Desenvolvido por Samio Santos</p>
    </footer>
  </body>
</html>